hotosm/MapCampaigner

campaign_manager/models/campaign.py
campaign_manager/selected_functions/_abstract_insights_function.py
campaign_manager/selected_functions/count_feature.py
campaign_manager/templates/campaign_detail.html
campaign_manager/templates/campaign_widget/ui/piechart.html
campaign_manager/views.py

update detail to use widget

---

campaign_manager/models/campaign.py
campaign_manager/selected_functions/_abstract_insights_function.py
campaign_manager/views.py

URL : /campaign_manager/campaign/96224fd319834166b3dbc564d9e98a13/function-1/metadata

added api for giving metadata

---

flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/views.py

Tell user if the area map is too big

---

flask_project/campaign_manager/templates/index.html

Change campaign list view to table in homepage

---

flask_project/campaign_manager/templates/create_campaign.html

Add tooltip for insight function

---

flask_project/campaign_manager/data_providers/osmcha_provider.py
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_error.html

- Pretify data without tag in data
- Correcting link on the UI
here is the description about osmcha
https://github.com/hotosm/field-campaigner/wiki/Data-Provider#3-osmcha-error-provider

pretify data from osmcha

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/utilities.py

Cached results for 15 minutes

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/templates/create_campaign.html

Make author as a default manager and manager input required

---

flask_project/campaign_manager/insights_functions/_abstract_insights_function.py
flask_project/campaign_manager/insights_functions/osmcha_error.py
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_error.html
flask_project/campaign_manager/templates/campaign_widget/ui/piechart.html

Fix bugs :
- chart is not shown because of empty data
- table is not shown for multiple table

fix bug on empty chart and double table

---

flask_project/campaign_manager/templates/new_base.html

Fix loading overlay in login

---

flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/templates/new_base.html

Show user location from browser

---

deployment/docker/requirements.txt
flask_project/campaign_manager/__init__.py
flask_project/campaign_manager/api.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/models/json_model.py
flask_project/campaign_manager/templates/campaign_widget/navigation.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/views.py

- Request campaign with ajax request
- Show nearest campaigns if user location available (#76)
- If not shows all campaigns
- Add button to show all available campaigns even if user location available

Filter table

---

flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/campaign_widget/ui/upload_boundary.html
flask_project/campaign_manager/templates/campaign_widget/ui/upload_coverage.html

fix bug on shapefile uploader on firefox

---

flask_project/campaign_manager/test/helpers.py
flask_project/campaign_manager/test/test_osmcha_error.py

add osmcha error unittest

---

flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/new_base.html

Fix bug if there is no user location from osm

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/templates/create_campaign.html

Campaign creation wizard 

---

flask_project/campaign_manager/test/test_feature_attribute_completeness.py

add feature attribute completeness test

---

.travis.yml
flask_project/campaign_manager/test/test_upload_coverage.py
flask_project/reporter/test/test_osm.py
flask_project/reporter/test/test_pep8.py

add travis test

---

flask_project/campaign_manager/templates/campaign_detail.html

Fix manage button showing up after log out

---

flask_project/campaign_manager/static/libs/leaflet-google-places-autocomplete/leaflet-gplaces-autocomplete.css
flask_project/campaign_manager/static/libs/leaflet-google-places-autocomplete/leaflet-gplaces-autocomplete.js
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/views.py

Add search location in create campaign map

---

flask_project/campaign_manager/templates/create_campaign.html

Restrict draw polygon to single polygon

---

flask_project/campaign_manager/data_providers/shapefile_provider.py

Fix error uploading shapefile

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/test/test_api.py

Show total all campaigns

---

flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/views.py

Make google api key not mandatory

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/templates/campaign_detail.html

add total contributors api

---

flask_project/campaign_manager/git_utilities.py
flask_project/campaign_manager/views.py

this partial fix #79 
Added git utilities when create/edit campaign

added git utilities

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/create_campaign.html

Update ui to add/edit campaign
The difference is in the campaign status and campaign name

update add or edit campaign ui

---

flask_project/campaign_manager/data_providers/tasking_manager.py
flask_project/campaign_manager/static/js/remote-mapping.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py

Now it works with staging server, it has been tested.

Fix XmlHttpRequest error for remote mapping

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/insights_functions/_abstract_insights_function.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_insight_function.py
flask_project/campaign_manager/insights_functions/count_feature.py
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/views.py

this fix #146 
- changing feature of insight function as freeform, so we could input anything
For example 
We could filter it by type of feature, like this, will return just place_of_worship for amenity

update feature of insight function as freeform

---

flask_project/campaign_manager/insights_functions/_abstract_overpass_insight_function.py

fix buildings feature

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_detail.html

Add share to twitter button

---

flask_project/campaign_manager/templates/about.html
flask_project/campaign_manager/templates/campaign_widget/navigation.html
flask_project/campaign_manager/views.py

add about page

---

flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/js/create/types_tags.js
flask_project/campaign_manager/templates/create_campaign.html

Select step in create/edit campaign

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/templates/index.html

Add campaign status filter in api

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/views.py

save dashboard settings

---

flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/views.py

Add participate action

---

flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/create_campaign.html

add Maps.me and OMK Android Link

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_changesets.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_features.html
flask_project/campaign_manager/templates/new_base.html

Add side panel in detail view

---

flask_project/campaign_manager/static/js/create/types_tags.js
flask_project/campaign_manager/templates/create_campaign.html

Added type selection in quality insights form

---

flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/views.py

add current user as default manager when manager is empty

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/js/create/map.js
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/mapper_engagement.html
flask_project/campaign_manager/templates/campaign_widget/ui/piechart.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py

Update Coverage Behaviour

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/views.py

- Add link to omk selection
- Disabled some share button in desktop

Link to OMK selection

---

flask_project/campaign_manager/static/css/create-campaign.css

Fix bouncy checkbox

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html

Dashboard show all

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/templates/create_campaign.html

disable manual text input

---

flask_project/campaign_manager/templates/create_campaign.html

change end date if it is before start date

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/insights_functions/__init__.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/insights_functions/osmcha_changesets.py
flask_project/campaign_manager/insights_functions/osmcha_features.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_changesets.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_features.html

Fix bugs in osmcha insight function

---

flask_project/campaign_manager/templates/create_campaign.html

fix datepicker bug

---

flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html
flask_project/campaign_manager/utilities.py

change 0/0 to n/a

---

flask_project/campaign_manager/static/js/create/map.js
flask_project/campaign_manager/static/js/create/remote_mapping.js
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/static/js/map-campaigner.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_changesets.html
flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html
flask_project/campaign_manager/templates/create_campaign.html

Fix campaign not showing coverage completed

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/insights_functions/count_feature.py
flask_project/campaign_manager/insights_functions/feature_attribute_completeness.py
flask_project/campaign_manager/templates/campaign_widget/ui/mapper_engagement.html
flask_project/reporter/osm_way_parser.py
flask_project/reporter/utilities.py

Add nodes in query

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/mapper_engagement.html
flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html
flask_project/campaign_manager/templates/create_campaign.html

UI updates

---

flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html

Shows contribution frequency in one graph

---

flask_project/campaign_manager/utilities.py
flask_project/reporter/exceptions.py
flask_project/reporter/osm.py

this fix #257 
checking by data returned by osm
if "elements" is not presented, show old data
"elements" is the list that contains features

show old data if there is no elements returned from osm

---

flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/insights_functions/osmcha_changesets.py
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_changesets.html
flask_project/campaign_manager/templates/campaign_widget/ui/osmcha_features.html

Fix osmcha table error

---

flask_project/campaign_manager/data_providers/tasking_manager.py
flask_project/campaign_manager/static/js/create/remote_mapping.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/create_campaign.html

Fix remote project search

---

flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/views.py

Fix participate

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html

Fix unexpected token

---

flask_project/campaign_manager/utilities.py

Simplify polygons if it gets too complex

---

flask_project/campaign_manager/models/campaign.py
flask_project/reporter/osm_way_parser.py
flask_project/reporter/utilities.py

Simplify polygon for overpass request

---

flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/insights_functions/count_feature.py
flask_project/campaign_manager/insights_functions/feature_attribute_completeness.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html
flask_project/campaign_manager/templates/campaign_widget/ui/piechart.html

Based on the feedback, I added features on the map.

Show features on map [In Progress]

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html

Show date in attribute completeness table

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/test/test_api.py

Add participants count to model

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_detail.html

This will only open maps me app in iOS, (fix #316)

Open maps me app if installed for iOS 

---

flask_project/campaign_manager/templates/campaign_detail.html

Fix https://github.com/hotosm/field-campaigner/issues/315

Remove remote mapping from areas covered

---

flask_project/campaign_manager/data_providers/_abstract_osmcha_provider.py

Improve OSMCHA filtering

---

flask_project/campaign_manager/models/campaign.py

Fix Campaigns with today's date do not show up

---

flask_project/campaign_manager/templates/index.html

Papercuts https://github.com/hotosm/field-campaigner/issues/330

Fix landing page

---

flask_project/campaign_manager/data_providers/overpass_provider.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/utilities.py
flask_project/reporter/osm.py

Fix https://github.com/hotosm/field-campaigner/issues/327

Query to overpass with element ids for mapper engagement

---

flask_project/campaign_manager/templates/index.html

fix no cards show

---

flask_project/campaign_manager/data_providers/tasking_manager.py
flask_project/campaign_manager/static/js/create/remote_mapping.js
flask_project/campaign_manager/templates/campaign_detail.html

Update to http://tm3.hotosm.org

Update remote mapping api to new server

---

flask_project/campaign_manager/static/js/create/map.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/views.py

fix #338 
landing page
details page
create AOI

change basemap

---

flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py

this fix #329 
i created 4 campaign
1. active 
2. inactive expired (enddate is expired)
3. inactive future (startdate is in future)
4. remote mapping (in the future but has remote mapping)
here is status that is in detail:
maybe we need add toggle on home too? to just show all/active/inactive/remotemapping?

change project status

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/views.py

fix #328 
the aerial imagery url is `http://{s}.aerial.openstreetmap.org.za/ngi-aerial/{z}/{x}/{y}.jpg`

add aerial map to the list

---

flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/index.html

Update select dropdown looks in safari

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/utilities.py

Get nearest campaigns from ip address

---

flask_project/campaign_manager/data_providers/_abstract_osmcha_provider.py
flask_project/campaign_manager/insights_functions/osmcha_changesets.py
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py

Fix https://github.com/hotosm/field-campaigner/issues/309

Combine error table

---

flask_project/campaign_manager/templates/index.html

show map all the time

---

flask_project/campaign_manager/insights_functions/osmcha_changesets.py
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html
flask_project/campaign_manager/views.py

Download josm file

---

flask_project/campaign_manager/insights_functions/feature_attribute_completeness.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/js/create/types_tags.js
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/modals/custom-types-and-tags.html

this fix #358 
Add custom type:
Edit Custom
Demo:
https://drive.google.com/file/d/0B7OxCB3EJZ5cdzlydUE3Q2hKZmc/view?usp=sharing

added custom type on create/edit field campaigner

---

flask_project/campaign_manager/insights_functions/feature_attribute_completeness.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html

fix #357 
any ideas where to put the legend @MariaSolovyeva ?

change color based on completeness

---

flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html

change color completeness

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html

add list attributes

---

flask_project/campaign_manager/insights_functions/feature_attribute_completeness.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html

fix #370 
Exclude warning on completeness count:

Warning completeness

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/js/detail/insight_functions.js
flask_project/campaign_manager/templates/campaign_detail.html

fix #365 
When there are a lot of contributors:
When there are few contributors:

fix legend contributors chart

---

flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/index.html

use elipsis to cut the text

---

flask_project/campaign_manager/static/js/detail/insight_functions.js

fix #385 
This solved the problem when the browser hang on campaign that uses lots of function which loads lots of data. So when this open campaign with enormous amount of data, browser won't be unresponsive (hang), it'll just get a lag.

improve browser performance

---

.gitignore
flask_project/app.py
flask_project/campaign_manager/templates/403.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py

- Only allow predefined managers to create a campaign
Fix #363

Temporarily pre defined managers

---

deployment/docker-compose.yml
flask_project/campaign_manager/data_providers/overpass_provider.py

Move the attic data server url setting to docker compose

fix attic data server url

---

flask_project/campaign_manager/static/js/create/campaign-json-handler.js
flask_project/campaign_manager/templates/create_campaign.html

fix #397 
This PR:
- Fix parsing geometry json data
- Fix rendering insight functions when submit the campaign

fix geometry parse json and adding functions upon editing

---

flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/campaign_widget/navigation.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/index.html

fix #391 
This PR:
home page *updated*:
create campaign page:
About page

[wip] add additional text

---

flask_project/campaign_manager/forms/campaign.py
flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/css/leaflet-search/leaflet-search.css
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/403.html
flask_project/campaign_manager/templates/about.html
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_widget/navigation.html
flask_project/campaign_manager/templates/campaign_widget/ui/upload_boundary.html
flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/templates/resources.html
flask_project/campaign_manager/views.py

PR for updates to text, adds a new page, and rearranges a few layout items: 
* updates front page text
* updates about page text
* adds resources page with placeholder text
* rearranges nav bar with resources page
* improves create campaign text and layout

Updates to layout, text, adds resources page

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/campaign_detail.html

update detail campaign style

---

flask_project/app_config.py
flask_project/campaign_manager/campaign_serializer.py
flask_project/campaign_manager/models/models.py
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/templates/modals/create-or-copy-campaign.html
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/views.py

fieldCampaigner: Test models with mock data
fieldCampaigner: Test models with mock data
FieldCampaigner: Add Selected Function Table, Add redis Structure for Reminders, Add MySql support
FieldCampaigner: shift from Flask- SQLAlchemy to SQlAlchemy, Add Feature Template Model
FieldCampaigner: Add postgresql database with postgis support, modify view for index.html
FieldCampaigner: Fetch and display data for index.html from database
FieldCampaigner: Render database content for campaign_detail.html
fieldCampaigner: provide database support to create/edit Campaign
FieldCampainger: Add component to register User Email, Implement nearest/all/inactive campaign view, extracted GeoJSON data from WKB
FieldCampaigner: Implement Edit Campaign view
extract geojson data
resolved edit campaign issue …

fieldCampaigner: Add Copy Campaign Feature

---

flask_project/app.py
flask_project/campaign_manager/campaign_serializer.py
flask_project/campaign_manager/context_processor.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_insight_function.py
flask_project/campaign_manager/insights_functions/_abstract_overpass_user_function.py
flask_project/campaign_manager/models/models.py
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/modals/create-or-copy-campaign.html
flask_project/campaign_manager/test/test_models.py
flask_project/campaign_manager/views.py

- Implement Insight-function functionality
- Implement addition of remote projects

implement insight functions and remote mapping

---

deployment/docker/requirements.txt
flask_project/app.py
flask_project/app_config.py
flask_project/campaign_manager/campaign_serializer.py
flask_project/campaign_manager/models/models.py
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/views.py
flask_project/profiling-ab.py

1.) Flask-Profiler: with admin authentication, keeps statistics of no. of user visits on a given URL, average visits in a given period, average time taken.
2.) Apache Bench: automated requests generation for a given URL.
3.) Line-Profiling: Line-by-Line profiling of the code to find out the bottlenecks during queries.
4.) Sentry-integration.

Added Flask extensions for debugging and profiling

---

.travis.yml
flask_project/app.py
flask_project/app_config.py
flask_project/app_sockets.py
flask_project/campaign_manager/models/models.py
flask_project/campaign_manager/sqlalchemy_session.py
flask_project/campaign_manager/templates/new_base.html
flask_project/campaign_manager/test/test_integration.py
flask_project/campaign_manager/test/test_models.py
flask_project/campaign_manager/views.py

Added new crud tests
segregate test and prod databases
shifted logic to models

Crud, Integration for fieldcampaigner

---

flask_project/campaign_manager/campaign_serializer.py
flask_project/campaign_manager/models/models.py
flask_project/campaign_manager/static/surveys/buildings
flask_project/campaign_manager/static/surveys/cafe
flask_project/campaign_manager/static/surveys/health-facilities
flask_project/campaign_manager/static/surveys/place-of-worship
flask_project/campaign_manager/static/surveys/restaurant
flask_project/campaign_manager/static/surveys/shops
flask_project/campaign_manager/static/surveys/supermarket

- Added survey folder containing template feature types for field campaigner.

template feature types

---

flask_project/campaign_manager/templates/create_campaign.html
flask_project/campaign_manager/templates/new_base.html

A bug occured if the user didn't fill area, team or when status is set to unassigned.
Surya is busy fixing his PR about team selection so in the meantime, I wrote a quick fix to prevent this bug.

area, team and status are required to successfully create a campaign

---

flask_project/campaign_manager/aws.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/test/test_s3_data.py

```
campaigns/
<campaign_uuid>/
campaign.json
campaign.geojson
thumbnail.png
campaign.html
raw_data/
attic/
feature_1.xml
feature_2.xml
overpass/
feature_1.json
feature_2.json
osm_changesets/
osm_features/
processed_data/
feature_attribute_completeness/
feature_1.json
feature_2.json
count_feature/
feature_1.json
feature_2.json
mapper_engagment/
osm_changesets/
osm_features/
html/
```

update s3 folder structure

---

.travis.yml
.travis/Dockerfile
.travis/deploy_lambda_functions.py

Deployment is triggered by Travis after a push(only if tests are successful) to the branch develop or master. 
TODO:

Lambda functions deployment script

---

lambda_functions/download/attic_data/aws.py
lambda_functions/download/attic_data/lambda_function.py
lambda_functions/download/attic_data/parser.py
lambda_functions/download/attic_data/requirements.txt
lambda_functions/download/attic_data/test.py
lambda_functions/download/attic_data/utilities.py
lambda_functions/download/features/aws.py
lambda_functions/download/features/campaign.py
lambda_functions/download/features/json_model.py
lambda_functions/download/features/lambda_function.py
lambda_functions/download/features/requirements.txt
lambda_functions/download/features/test.py
lambda_functions/download/features/test_helper.py
lambda_functions/download/features/utilities.py
lambda_functions/download/features/version.py
lambda_functions/download/overpass_data/aws.py
lambda_functions/download/overpass_data/campaign.py
lambda_functions/download/overpass_data/json_model.py
lambda_functions/download/overpass_data/lambda_function.py
lambda_functions/download/overpass_data/requirements.txt
lambda_functions/download/overpass_data/test.py
lambda_functions/download/overpass_data/utilities.py
lambda_functions/download/overpass_data/version.py

There are 6 lambda functions
The `init` function is called by the `compute_campaign` function. See Compute Lambda functions. This function invokes the asynchronous execution of the `features` , `osm_changesets` and `osm_features` lambda functions. 
Parameters sent: campaign’s uuid.
A campaign might have more than one feature.
The `features` function will invoke the asynchronous execution of the  `overpass_data` function for each feature of the campaign.
Parameters sent: campaign’s uuid., feature’s key and feature’s values
This function builds a query to send to Overpass.
The response is saved in S3.
Then, it calls the `attic_data` function.
Parameters sent: campaign’s uuid, overpass filename, and the campaign’s date_start and date_end. 
In order to build the query, the `attic_data` …

[WIP] lambda download functions

---

flask_project/app_config.py
flask_project/campaign_manager/aws.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py
requirements.txt

The compute_campaign lambda function is invoked after the creation of a campaign.
A warning message is displayed until the data is available to render.

wip SHOW campaign page

---

.ebextensions/environment.config

removed OVERPASS_URL, ATTIC_URL; 
added AWS_DEFAULT_REGION

Edit Beanstalk env variables configuration

---

lambda_functions/render/feature/aws.py

fix render lambda function

---

flask_project/campaign_manager/templates/campaign_detail.html

Campaign Page

---

lambda_functions/process/count_feature/parser.py

count_feature lambda function

---

flask_project/campaign_manager/templates/campaign_detail.html
lambda_functions/render/feature/templates/content.html
lambda_functions/render/feature/templates/map.html

Render function

---

flask_project/campaign_manager/templates/campaign_detail.html

We had to load twice the page to see the user contributions.

fix fetching mapper-engagement.json

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_detail.html

Something's wrong with the dates
what do you think?

Fix top panel

---

lambda_functions/download/overpass_data/campaign.py

There were a bug to download overpass data when a geojson has more than one polygon.

geojson with multiple polygons

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/templates/index.html

use js promises to load campaigns on the landing page

Speed up Landing page

---

flask_project/campaign_manager/templates/campaign_detail.html
lambda_functions/process/feature_attribute_completeness/test.py
lambda_functions/render/feature/templates/errors.html
lambda_functions/render/feature/templates/map.html
lambda_functions/render/feature/test.py

use cluster to display large amount of markers.
add click event to each marker.
datatables was too slow: rewrite basic pagination.

improve campaign page performance.

---

.travis/deploy_lambda_functions.py

It was set to 3 seconds.
Increased to 300 seconds.

increase lambda timeout

---

flask_project/campaign_manager/views.py
lambda_functions/compute/campaign/aws.py
lambda_functions/compute/campaign/lambda_function.py
lambda_functions/compute/campaign/test.py

Removed as well data from S3 before computing the campaign again.

compute campaign after edition

---

lambda_functions/render/feature/templates/errors.html
lambda_functions/render/feature/templates/map.html

Half of the time, the map doesnt render properly. Used invalidateSize…(leaflet).
Rendering a lot of errors would freeze the browser.

Speed up campaign page.

---

flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py
lambda_functions/render/feature/templates/map.html

Use Mapbox map for the landing page's map.

---

flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py
lambda_functions/render/feature/templates/map.html

Fixed #573.
Lambda function to update:
- render_feature

Areas covered

---

flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html

Disable multypoligons

---

lambda_functions/download/overpass_data/campaign.py
lambda_functions/download/overpass_data/lambda_function.py
lambda_functions/download/overpass_data/test.py
lambda_functions/download/overpass_data/utilities.py

Fixed #596 (see comments on the issue)

Remove features that are outside the campaign's area.

---

flask_project/campaign_manager/templates/modals/custom-types-and-tags.html

Add a drop-down list to select an element type (point, line, polygon).

---

flask_project/campaign_manager/templates/new_base.html

Piwik code will be removed later.

Add matomo tracking code

---

flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/index.html

This pull request closes issue #623 
The active/inactive indicator is showed as a color circle. Please check figure below.

Include active/inactive indicator

---

flask_project/campaign_manager/templates/index.html

This pull request closes #624. The changes are shown in the GIF below.

Included active option to show only active campaigns

---

flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py

The Maps.me button is not working because the function that is executed when this button is pressed was removed on this commit 17789b1f00ea91e6e8220be446162160a720f687
I present in this Pull request a similar approach, using the following tasks:
- When the button is pressed, I fetch data points from leaflet map.
- Then, an ajax request is performed to the _/generate_kml_ handler that parses the json file with data points and creates a kml, which is saved within the CACHE_DIR path.
- If the request is successfull, the server returns the url for the file to be downloaded.
- I also created a alert-success div on the page but I hid it. Just in case, we can show it after successful request.
I also show a screen recording in my mobile device:
http://recordit.co/Xb3a2o9WbF
**Note.** The …

Download kml file for Maps.me

---

.travis/deploy_lambda_functions.py

Increase lambda timeout from 300 to 900

---

flask_project/campaign_manager/aws.py
flask_project/campaign_manager/test/test_s3_data.py
flask_project/campaign_manager/test/test_survey.py

Some tests were using the list command from the s3 data module.

Fix missing tests removing the modified field

---

.travis/deploy_lambda_functions.py
README.md
deployment/docker/requirements.txt
flask_project/campaign_manager/api.py
flask_project/campaign_manager/aws.py
flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/models/survey.py
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/index.html
flask_project/campaign_manager/test/test_s3_data.py
flask_project/campaign_manager/test/test_survey.py
flask_project/campaign_manager/test/test_thumbnail.py
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py
lambda_functions/compute/campaign/aws.py
lambda_functions/compute/campaign/lambda_function.py
lambda_functions/download/errors/lambda_function.py
lambda_functions/download/features/lambda_function.py
lambda_functions/download/overpass_data/lambda_function.py
lambda_functions/process/count_feature/lambda_function.py
lambda_functions/process/feature_attribute_completeness/lambda_function.py
lambda_functions/process/feature_attribute_completeness/test.py
lambda_functions/process/mapper_engagement/lambda_function.py
lambda_functions/render/feature/lambda_function.py
requirements.txt

Includes the following work: 
* include status indicator #629 
* Remove show map checkbox #635 
* only show active by default #636 
* update installation procedure #630 
* fix thumbnail generation #638 
* fix maps.me button and download #637 
* increase lambda timeout #633 
* Add error message for campaigns that do not render #607 
* improve landing page loading speed #641 
thanks @pierrealixt @JorgeMartinezG for the nice work on all these! 🚀

Deploy latest to production

---

flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py

This pull request consists of including a **Download** button on the detail campaign page. This button when pressed, creates a csv file which contains the contributions of each user by date per feature type.
The corresponding csv file is also allocated on the CACHE_DIR path.

Download user contributions

---

flask_project/campaign_manager/aws.py

**Issue**
When the application makes a request to retrieve the list of campaigns from an s3 bucket, if the number of campaigns is high (production environment), AWS limits the amount of the returned keys to 1000, making campaigns not to be listed within the landing page.
**Approach**
This PR modified the list method from the S3DATA class, with the purpose of checking if all the data has been returned using continuation tokens. When this process is over, returns the complete number of campaigns included in the bucket.

Fetch multiple requests to s3 to get list of data

---

flask_project/campaign_manager/templates/modals/custom-types-and-tags.html

For deployment purposes, the enhancement of the yaml checker is removed in this commit. Leaving the types-and-tags.html file as it was previously.
The yaml checker improvement is gonna be added in the upcoming days and tested further

Rollback Types and tags file

---

flask_project/campaign_manager/static/css/create-campaign.css
flask_project/campaign_manager/static/css/map-campaigner.css
flask_project/campaign_manager/static/js/create/modal.js
flask_project/campaign_manager/static/js/create/types_tags.js
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/modals/modal_main.html
flask_project/campaign_manager/views.py

This pull request includes 4 commits that fixes 4 issues, which are enumerated below:
1. Positioning edit and remove buttons correctly within the create campaign page. Closes #670 
2. Remove duplicated campaign when campaign name changes. Closes #626 
3. Include loading indicator and refresh button when campaign is still computing. Closes #671 
4. Remove repeated rows when generating csv file. Closes #672

 Multiple fixes

---

flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html

This pull request closes #644.
- The _isMultipolygon_ function is modified to check also LineString geometry.

alert error when uploading linestring geojson file

---

flask_project/campaign_manager/templates/campaign_widget/ui/upload_fieldpaper.html

This PR allows the application to check for any element with null values within an uploaded geojson file. Closes #609

Check for any null element when geojson upload

---

flask_project/campaign_manager/static/css/campaign-detail.css
flask_project/campaign_manager/templates/campaign_detail.html

This PR closes issues #684 and #685 .

Fixes for chart visualization

---

.travis/deploy_lambda_functions.py
.travis/deploy_lambda_functions_hotosm.py
lambda_functions/process/make_vector_tiles/index.js

Fix module export, runtime and handler values. Increase timeout and memory.

fix nodejs lambda invocation

---

lambda_functions/process/make_vector_tiles/index.js

Fix S3 upload

---

flask_project/campaign_manager/models/campaign.py
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/views.py

Previously, Maps.me button worked using data fetched from leaflet map. Because the project plan is to apply vector files, we would need to fetch the geojson for each feature for the `generate_kml` function.
This PR modifies the generate_kml handler for Maps.me with the purpose of fetching the geojson data from the s3 bucket instead of reading from leaflet

Read geojson data from s3 instead of leaflet

---

lambda_functions/process/feature_attribute_completeness/parser.py
lambda_functions/process/feature_attribute_completeness/utilities.py

This PR closes #744. For every xml tag, there is a check which discards elements given the element_type

Remove elements when element_type is set

---

.travis.yml

Build assets aren't being deployed. This should fix it (maybe) 🤞🏻

Add local_dir to deploy

---

flask_project/campaign_manager/views.py

Switch function params order

---

flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_detail/map.html
flask_project/campaign_manager/utilities.py
flask_project/campaign_manager/views.py

This PR closes #724 
When the user clicks within the AOI and there is a collected feature, It shows the feature information. When there is no feature. It shows a popup with a button to OSM id editor

GPX feature

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/aws.py
flask_project/campaign_manager/templates/campaign_index.html
flask_project/campaign_manager/views.py
flask_project/reporter/utilities.py

Adds osm_id filtering based on user.json array

updated filter functionality on my projects page

---

flask_project/campaign_manager/templates/campaign_detail/map.html
flask_project/campaign_manager/views.py

This feature is included in both frontend and backend.

Download mbtiles feature

---

flask_project/campaign_manager/views.py
lambda_functions/download/overpass_data/lambda_function.py
lambda_functions/download/overpass_data/utilities.py
lambda_functions/process/make_feature_json/lambda_function.py

Compute stats from each feature file instead of campaign.json

---

lambda_functions/process/make_feature_json/lambda_function.py

fixes issue where s3data object incorrectly parses xml via fetch method (only handles json and yml)

fix xml read from s3

---

flask_project/campaign_manager/api.py

adds endpoint in api.py to allow downloading project PDFs in zipfile bundles

pdf bundle download endpoints

---

flask_project/campaign_manager/api.py
flask_project/campaign_manager/templates/campaign_detail/table.html

update all features to api endpoint and updated fetch route for campaign detail

API endpoint to merge all feature json

---

flask_project/campaign_manager/templates/base.html
flask_project/campaign_manager/templates/campaign_base.html
flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/components/project_header.html
flask_project/campaign_manager/views.py

- Removed repeated login and logout handlers.
- store within server side the user id and name

Handle project edit/delete on the server side

---

flask_project/campaign_manager/styles/components/_progress.scss
flask_project/campaign_manager/templates/campaign_detail/contributors_ranking.html
flask_project/campaign_manager/views.py

This solves the issue when there are less than 5 contributors

Render contributors based on context data

---

flask_project/campaign_manager/templates/campaign_widget/ui/upload_file.html

Closes #827 . the _map-notification-holder_  div does not exist within the whole project

Replace notification holder to display map errors

---

flask_project/campaign_manager/templates/campaign_detail.html
flask_project/campaign_manager/templates/campaign_index.html
flask_project/campaign_manager/utilities.py

fixes current NaN in user overview page

Hot fix/feature counts
