hotosm/MapCampaigner

flask_project/campaign_manager/insights_functions/_abstract_insights_function.py, flask_project/campaign_manager/insights_functions/upload_coverage.py, flask_project/campaign_manager/models/campaign.py, flask_project/campaign_manager/templates/campaign_detail.html, flask_project/campaign_manager/templates/campaign_widget/ui/feature_completeness.html, flask_project/campaign_manager/templates/new_base.html
this fixes #54, fixes #52 
only show incomplete
For manager only insight function, added new attribute for insight function (manager_only, default is false). It will not show if profile_name of osm is not in manager of campaign.
Because we don't have session in the backend, the idea is now we are waiting for getting profile detail, after that render insight function based on the rule of manager_only. 
Show if:
- manager_only is false
- manager_only is true and profile_name is in manager of campaign
=> added manager_only attribute for insight function

flask_project/campaign_manager/data_providers/shapefile_provider.py, flask_project/campaign_manager/templates/campaign_widget/ui/upload_boundary.html, flask_project/campaign_manager/views.py
This fix #126 
Restrict upload boundary form for just single shapefile
=> update boundary uploader to just receive single polygon

flask_project/campaign_manager/static/css/create-campaign.css, flask_project/campaign_manager/templates/create_campaign.html
fix #158 
Start date can be picked until `end date`
End date can be picked start from `start date`
note: this PR also change the position of campaign name input in the form
=> add date validator

flask_project/campaign_manager/templates/create_campaign.html
fix #369 
In the edit view, when the user is not the manager of the campaign, he will be redirected to 404.
for the manager, edit is working as usual
=> strict edit view for managers

flask_project/campaign_manager/data_providers/overpass_provider.py
Tried this in my local.
Using `http://ec2-54-172-198-122.compute-1.amazonaws.com/api/interpreter` is better at acquiring data. As using the previous one, sometimes I get `network error` when loading the campaign, but not using this one.
=> change overpass server url

flask_project/campaign_manager/static/css/create-campaign.css, flask_project/campaign_manager/static/js/create/campaign-json-handler.js, flask_project/campaign_manager/static/js/create/types_tags.js, flask_project/campaign_manager/templates/create_campaign.html, flask_project/campaign_manager/templates/modals/custom-types-and-tags.html
this fixes hotosm/field-campaigner/issues/450, fixes hotosm/field-campaigner/issues/448
Is this something like this @smit1678 ?
When user click "add custom type", there is button to change to yaml editor
When user click "Edit custom types in yaml", it will open yaml editor and shows all data of custom types in yaml and can edit/add it .
DEMO : 
https://drive.google.com/file/d/1AFDrlb-QW-NBzBKukJ_3SyJWMku7V63N/view?usp=sharing
=> add yaml survey editor

flask_project/campaign_manager/test/test_s3_data.py
On Travis, tests are running against HOTOSM AWS account and the bucket's name is `hotosm-fieldcampaigner-data-test`.
=> fix aws test on travis

.ebextensions/environment.config, flask_project/campaign_manager/aws.py, flask_project/campaign_manager/models/campaign.py, flask_project/campaign_manager/templates/index.html
The code that generated the static map was called during the processing of one insight function.
It is now called after campaign creation (and edition).
However there is still an issue:
on the actual production:
on my local machine:
=> Generate thumbnail

flask_project/campaign_manager/templates/campaign_detail.html, lambda_functions/render/feature/templates/errors.html, lambda_functions/render/feature/templates/map.html
Half of the time, the map would not display properly.
I fixed it by encapsulating the `fitBounds` methods into `setTimeout`.
I also set the config `cache: false` to all AJAX queries.
=> fix map init

flask_project/campaign_manager/models/campaign.py, flask_project/campaign_manager/views.py
thumbnail url was not properly saved in campaign.json after campaign creation.
=> save thumbnail url 

flask_project/campaign_manager/views.py
In issue #589, the campaign has been created with a wrong map_type:
If `map_type` isn't in the attributions list, it crashes.
It should returns nothing if it isn't present.
Fixed #589.
=> fix wrong campaign's map_type -> error 500

lambda_functions/download/errors/aws.py, lambda_functions/download/errors/lambda_function.py, lambda_functions/download/errors/requirements.txt, lambda_functions/download/errors/test.py, lambda_functions/download/errors/utilities.py, lambda_functions/process/feature_attribute_completeness/lambda_function.py, lambda_functions/process/feature_attribute_completeness/parser.py, lambda_functions/process/feature_attribute_completeness/utilities.py, lambda_functions/render/feature/templates/errors.html
This OSM file is generated into a new Lambda function: download_errors.
This function is invoked from the process_feature_attribute_completeness function.
Fixed #553.
Lambda functions to update:
* process_feature_attribute_completeness
* render_feature
Lambda function to create:
* download_errors
=> Download errors/warnings as OSM file

.travis/deploy_lambda_functions.py
Without the region, the following command `aws lambda list-functions` would return nothing.
Adding the region argument `--region us-west-2` seems to fix this problem.
Fixed #501
=> Added the region argument to the list-functions AWS command.

flask_project/campaign_manager/templates/index.html
This pull request closes issue #625. You can check the commit in the figure below.
**Option 2.** IMO I consider better to switch positions between search bar and the _showing_ option. Like the following figure. If you are agree that this option is better, I will update this PR with a new commit
Let me know your opinions
=> Remove show map checkbox in landing page

deployment/docker/requirements.txt, flask_project/campaign_manager/models/campaign.py, flask_project/campaign_manager/test/test_thumbnail.py, requirements.txt
Fixed #592 
3 campaigns had their thumbnails not generated. I found out two reasons:
- campaign's geojson were too big, more than 20000 characters. MapBox API would return `BAD URL`.
- campaign's geojson had `properties` and somehow that would cause MapBox to fail at parsing the geojson.
I used [this library](https://github.com/fitnr/visvalingamwyatt) to simplify the polygons.
=> Fix thumbnails generation

flask_project/campaign_manager/templates/campaign_detail.html, flask_project/campaign_manager/views.py
This PR contains two fixes related to the Maps.me button download:
1. It escapes not valid characters for the kml file generation. Data might have characters which are considered illegal for the kml library.
2. In the campaign detail page, two alerts are created when the kml file is created successfully or not. Please check figures below
=> Fixes for Maps.me kml download

flask_project/campaign_manager/templates/campaign_detail.html, lambda_functions/compute/campaign/aws.py, lambda_functions/compute/campaign/lambda_function.py, lambda_functions/download/errors/lambda_function.py, lambda_functions/download/features/lambda_function.py, lambda_functions/download/overpass_data/lambda_function.py, lambda_functions/process/count_feature/lambda_function.py, lambda_functions/process/feature_attribute_completeness/lambda_function.py, lambda_functions/process/feature_attribute_completeness/test.py, lambda_functions/process/mapper_engagement/lambda_function.py, lambda_functions/render/feature/lambda_function.py
I added a `try/except` in every lambda functions to catch errors that might crash the computation of a campaign.
The error is then stored in `failure.json` and displayed on the campaign page.
Fixed #558
=> Catch errors in lambda functions.

flask_project/campaign_manager/api.py, flask_project/campaign_manager/aws.py, flask_project/campaign_manager/templates/index.html, flask_project/campaign_manager/utilities.py
This Pull request consists on the retrieval of campaigns data and metadata from a storage cache folder. 
**Problem statement**
Every time a user loads the index page, for every campaign, a request is performed to get the campaign.json and campaign.geojson files. These filea are read from s3. Therefore, this process takes a lot of time reading and loading the information with ajax requests.
**Proposed approach**
- Instead of executing this task every time the page is loaded, the application stores the information within a cache folder. The path corresponds to the **CACHE_DIR** and it is defined using the _osm_app_ configuration folder 
- For every uuid read from the S3 list, the server checks if the json (and geojson) file is stored. If not, the server gets the information from amazon and …
=> Use a cache directory to store campaign data

flask_project/campaign_manager/test/test_s3_data.py
Because the returning data changed from list of uuids to list of dictionaries, we need to get the uuid field from the example dictionary on the test suite.
=> Get uuid from list of dictionaries in tests

flask_project/campaign_manager/utilities.py, flask_project/campaign_manager/views.py
Many campaign contributors have characters which are considered invalid due to locale configuration when writing into a file. This pull request forces the writer to use utf-8 without the need of encoding/ decoding between utf-8 and ascii.
=> Force file writer to use encoding utf-8

flask_project/campaign_manager/templates/modals/custom-types-and-tags.html
This pull request modifies the yaml modal to check on each category to include, that it has the required fields.
It also verifies that the category name has not been included previously. If it is, it returns an error.
=> Check for each type if it is repeated / refactor fields check

flask_project/campaign_manager/static/js/create/modal.js, flask_project/campaign_manager/templates/create_campaign.html, flask_project/campaign_manager/templates/modals/modal_form.html, flask_project/campaign_manager/templates/modals/modal_home.html, flask_project/campaign_manager/templates/modals/modal_main.html, flask_project/campaign_manager/templates/modals/modal_yaml.html
This pull request makes visualization changes on the create campaign view. Instead of having three different buttons to add campaign types using different modals, users are now able to click a single button to add types and tags within a single modal view. The options are:
- Using a template.
- Fill a custom form.
- Use a yaml editor.
The yaml editor includes a syntax checker and categories checker. The users must include **feature,** **tags** and **element_type** fields for each type.
With the yaml editor, users can include more than one campaign type.
When editing a campaign type, a modal will be displayed with two views. Users can modify the campaign type and tag using a yaml editor or the custom form.
**Notes.** 
- The duplicate campaign type when editing is not fixed on this PR.
- …
=> Create campaign types and tags using a single modal instead of three

flask_project/campaign_manager/templates/campaign_detail.html
This pull request is related to issue #617 .
This commit modifies the content.html file of a campaign. Because all the code that is used to create the chart is within this file, I applied string concatenation using regular expression, and replace in order to fullfill the required task.
IMO I consider this is not the best solution. Maybe modifying the content.html template directly could be a better way to solve the problem. However, it would be necessary to regenerate all content.html files for all campaigns. Feel free to comment
=> Modify bar chart from vertical to horizontal

lambda_functions/render/feature/templates/map.html
Instead of hardcoding the s3 url, the path is read from context dictionary sent on map.html generation
=> Read s3 path from context dictionary on map.html rendering

.travis.yml, deployment/docker-compose.yml, flask_project/campaign_manager/views.py, lambda_functions/download/attic_data/utilities.py, lambda_functions/download/errors/utilities.py, lambda_functions/download/overpass_data/utilities.py
This updates all places in the code that pointed to HOT's old overpass. We've updated our overpass to be at `overpass.hotosm.org`.
=> switch to new overpass url

lambda_functions/process/feature_attribute_completeness/parser.py
some instance attributes were only defined in methods and had the possibility of being skipped see:
https://github.com/hotosm/MapCampaigner/blob/214448d01977891694f3defcc414713b4c307625/lambda_functions/process/feature_attribute_completeness/parser.py#L109
and 
https://github.com/hotosm/MapCampaigner/blob/214448d01977891694f3defcc414713b4c307625/lambda_functions/process/feature_attribute_completeness/parser.py#L132
This should resolve issue #679
=> moved instance attrs to init, fixes #679

lambda_functions/download/overpass_data/utilities.py, lambda_functions/process/feature_attribute_completeness/parser.py
This PR modifies the _rebuild_osm_file_ with the goal of parsing correctly xml elements from files. You can find more information here: https://mail.python.org/pipermail/xml-sig/2005-January/010838.html
=> Use end event to parse xml elements when rebuilding osm file

lambda_functions/process/feature_attribute_completeness/lambda_function.py, lambda_functions/process/feature_attribute_completeness/parser.py
This PRs checks the feature name within the element tags for any campaign. If the condition is true, the element is not remove in the geojson creation.
=> Do not remove elements with feature name within element tags

flask_project/campaign_manager/styles/_campaigns.scss, flask_project/campaign_manager/styles/_labels.scss, flask_project/campaign_manager/styles/components/_buttons.scss, flask_project/campaign_manager/styles/templates/_footer.scss, flask_project/campaign_manager/templates/base.html, flask_project/campaign_manager/templates/components/small_footer.html
This resolves #732 
Basic markup and styles for this page are done. Left to do:
- ~~Update map styles and replace with mapbox-gl if possible (see #749 )~~
- ~~Implement pagination of search results?~~
=> Create user overview page

flask_project/app_config.py, flask_project/campaign_manager/styles/components/_buttons.scss, flask_project/campaign_manager/styles/pages/_campaigns.scss, flask_project/campaign_manager/styles/templates/_header.scss, flask_project/campaign_manager/templates/campaign_detail/map.html, flask_project/campaign_manager/templates/campaign_features.html, lambda_functions/render/feature/templates/map.html
- OSMCha url now is osmcha.org
- force map attribution to be `compact: false`
- link the entire feature type card, instead of only the red arrow
- add `cursor: pointer` to the switch toggle and remove right margin
- increase font-size on the top header. Resolves #811
=> update osmcha url, switch cursor, map attribution & feature type card link
